<?php
/**
 * @file
 * Module to implement zipcode proximity search.
 *
 * Module developed by James Barnett 2012 for thingsincommon website to
 * implement zipcode proxity searches to connect folks who live
 * near each other with "activities in common"
 */

include 'PHP-ZipCode-Class/zipcode.php';

/**
 * Implements hook_menu().
 */
function zipcode_search_menu() {
  $items = array();
  $items['zipcode-search'] = array(
    'title' => 'Activities in Common: Zip code search page (find folks to do fun stuff with)',
    'page callback'=>'drupal_get_form',
    'page arguments'=>array('zipcode_search_page_form'),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Implements an old function I'm no longer using and don't care to remove
 * an alternative way of calling the form.
 */
function zipcode_search_page() {
  global $user;
  $user_fields = user_load($user->uid);
  $content = '';
  $content .= drupal_render(drupal_get_form('zipcode_search_page_form'));
  $results = '';
  if ($_SESSION['myvalue']) {
    drupal_set_message('session myvalue is ' . $_SESSION['myvalue']);
    $results = zipcode_get_results($_SESSION['myvalue']);
  }
  $content .= '<br /> HELLO ' . $results;
  return $content;
}

/**
 * Implements hook_form().
 */
function zipcode_search_page_form($form, &$form_state) {
  if (isset($_SESSION['proximity'])) {
    $proximity = $_SESSION['proximity'];
  }
  else {
    $proximity = '';
  }
  if (isset($_SESSION['myvalue'])) {
    $zipcode_searched = $_SESSION['myvalue'];
  }
  else {
    $zipcode_searched = '';
  }
  $form['your_zipcode'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter your zipcode'),
    '#default_value' => $zipcode_searched,
    '#size' => 30,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  $form['proximity'] = array(
    '#type' => 'textfield',
    '#title' => t('Enter how far away in miles you want to find like minded people'),
    '#default_value' => $proximity,
    '#size' => 30,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  if (isset($_SESSION['myvalue'])) {
    $form_state['storage']['myvalue'] = $_SESSION['myvalue'];
    if ($path = libraries_get_path('DataTables')) {
      drupal_add_js(drupal_get_path('module', 'zipcode_search') . '/zipcode_search.js');
      drupal_add_js($path . '/media/js/jquery.dataTables.min.js');
      drupal_add_css($path . '/media/css/demo_table.css');
      drupal_add_css(drupal_get_path('module', 'zipcode_search') . '/zipcode_search.css');
    }
  }
  $content = '';
  if (!empty($_SESSION['myvalue']) && !empty($_SESSION['proximity'])) {
    // Display a message with the submitted value.
    $content = t("<br /><br />Your results near: <br /> " . $form_state['storage']['myvalue']);
    $content .= zipcode_get_results($_SESSION['myvalue'], $_SESSION['proximity']);
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#suffix' => $content,
  );

  return $form;
}

/**
 * Implements hook_form_validate().
 */
function zipcode_search_page_form_validate($form, &$form_state) {
  global $user;
  if (in_array('authenticated user', array_values($user->roles))) {
    $authenticated = TRUE; 
  }
  else {
    form_error($form, t('You must create an account on the left to complete your search.'));
  }
  $thezip = $form_state['values']['your_zipcode'];
  $sql = 'SELECT zip_code from zip_code where zip_code = :yourzip';
  $results = db_query($sql, array('yourzip' => $thezip));
  $aresult = '';
  foreach ($results as $result) {
    $aresult = $result->zip_code;
  }
  if (!$aresult) {
    form_error($form, t('you must pick a valid U.S. zipcode'));
  }
  if (!is_numeric($form_state['values']['proximity'])) {
    form_error($form, t('you must pick a numeric value in miles for proximity'));
  }
  if ($form_state['values']['proximity'] > 100) {
    form_error($form, t('You must limit your proximity search to within a 100 mile radius.'));
  }
 }

/**
 * Implements hook_form_submit().
 */
function zipcode_search_page_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  $_SESSION['myvalue'] = $form_state['values']['your_zipcode'];
  $_SESSION['proximity'] = $form_state['values']['proximity'];
  $form_state['storage']['myvalue'] = $form_state['values']['your_zipcode'];
}

/**
 * Implements getting which zipcodes are within a given proximity.
 */
function zipcode_get_results ($zipcode, $proximity) {
  mysql_connect('localhost:8889', 'root', 'Labrad0r');
  mysql_select_db('activities');
  $count = 1;
  $thezip = $zipcode;
  $framingham = new ZipCode($thezip);
  $content = "";
  $thezips = array();
  foreach ($framingham->getZipsInRange(0, $proximity) as $miles => $zip) {
    $miles = round($miles, 1);
    // $zip_results = "Zip code <strong>$zip </strong> is <strong>
    // $miles</strong> miles away from " " <strong>$framingham</strong><br/>";
    // $content .= $zip_results;
    // $thezips[] = "'" . $zip . "'";
    $thezips[] = $zip;
    $miles_away[] = $miles;
  }
  // Add the zipcode they actually searched for as well.
  $thezips[] = $zipcode;
  // The zipcode they searched for is 0 miles away from itself.
  $miles_away[] = 0;
  $people_sql = 'SELECT DISTINCT u.uid, u.name as name, m.field_marital_status_value as marital, z.field_zipcode_value as zip, group_concat(distinct(h.field_hobbies_value)) as hobbies from {users} u,
        {field_data_field_zipcode} z, {field_data_field_hobbies} h, {field_data_field_marital_status} m where z.entity_id = u.uid and h.entity_id = u.uid
        and z.field_zipcode_value IN (:zips) group by name';
  $people_results = db_query($people_sql, array(':zips' => $thezips));
  $thepeople = array();
  $count = 0;
  foreach ($people_results as $row) {
    $count = $count + 1;
    $thepeople[$count]['name'] = $row->name;
    $thepeople[$count]['zip'] = $row->zip;
    $thepeople[$count]['hobbies'] = $row->hobbies;
    $thepeople[$count]['marital'] = $row->marital;
    $thepeople[$count]['uid'] = $row->uid;
    $count = $count + 1;
  }
  $content .= '<h2>Thanks for being one of the early users of this site, we are growing by about 100+ members a day, check back soon to find more matches.</h2>';
  $content .= '<table id="datatable1">
  <thead>
        <tr>
            <th>Photo</th>
            <th>Name</th>
            <th>Zipcode</th>
            <th>Hobbies</th>
            <th>Marital Status</th>
            <th>Distance</th>
        </tr>
    </thead><tbody>';
  foreach ($thepeople as $person) {
    $search_value = $person['zip'];
    $keys = array_keys($thezips, $search_value);
    $profile = user_load($person['uid']);
    if (isset($profile->picture->uri)) {
      $user_pic = theme_image_style(
        array(
          'style_name' => 'medium',
          'path' => $profile->picture->uri,
          'attributes' => array(
            'class' => 'thumb',
            'width' => '60',
            'height' => '60',
          ),
          'width' => NULL,
          'height' => NULL,
        )
      );
    }
    else {
      $user_pic = '';
    }
    $marital = preg_replace('/_/', ' ', $person['marital']);
    $content .= '<tr><td>' . $user_pic . '</td><td>' . l(t($person['name']), 'user/' . $person['uid']) . '</td><td>' . $person['zip'] . '</td><td>' .
    $person['hobbies'] . '</td><td>' . $marital . '</td><td>' . $miles_away[$keys[0]] . ' miles away</td></tr>';
  }
  $content .= '</tbody></table>';
  if ($path = libraries_get_path('DataTables')) {
    drupal_add_js(drupal_get_path('module', 'zipcode_search') . '/zipcode_search.js');
    drupal_add_js($path . '/media/js/jquery.dataTables.min.js');
    drupal_add_css($path . '/media/css/demo_table.css');
  }
  return $content;
}
